services:
  - type: web
    name: epstein-files-api
    runtime: python
    buildCommand: "pip install -r requirements.txt && python -m db.database"
    startCommand: "gunicorn api.server:app --bind 0.0.0.0:$PORT"
    plan: basic

  - type: worker
    name: epstein-downloader
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m crawler.downloader"
    plan: basic
    envVars:
      - key: DATASET_FOCUS
        value: "10"
      - key: DOWNLOADER_WORKERS
        value: "3"
      - key: DOWNLOADER_JITTER_MIN
        value: "0.1"
      - key: DOWNLOADER_JITTER_MAX
        value: "0.4"
